# Generated by Django 4.2.2 on 2023-08-08 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias',
            name='destino',
        ),
        migrations.AddField(
            model_name='destino',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.materias'),
        ),
    ]
