# Generated by Django 4.2.2 on 2023-08-09 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_materias_destino_destino_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias',
            name='local',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destino',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos_local', to='stock.materias'),
        ),
        migrations.AlterField(
            model_name='destino',
            name='motivo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='destino',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos_name', to='stock.materias'),
        ),
    ]
