# Generated by Django 4.2.2 on 2023-08-09 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_materias_local_alter_destino_local_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destino',
            old_name='name',
            new_name='material',
        ),
    ]
